version: 1.2.1
zenodo_id: 17012181
sample: mmlong2
loc: none
sing: none
fastq: none
reads_diffcov: none
mode: Nanopore-simplex
binmode: default
seed: 15690701
proc: 3
proc_sub: 5
assembler: metaflye
custom_assembly: FALSE
assembly_info: FALSE
circ_prob: N
myloasm_cov: 1
myloasm_ovlp: 500
myloasm_bloom: 10
myloasm_extra: FALSE
flye_cov: 3
flye_ovlp: 0
medaka_status: FALSE
medaka_split: 30
medaka_usage: 10
medaka_batch: 200
medak_mod_pol: r1041_e82_400bps_sup_v5.0.0
curation_status: TRUE
min_dist: 500
min_len_zerocov: 100
clip_ratio: 0.9
min_cov_clip: 3
min_cov_clip_all: 3
tiara_status: TRUE
minimap_np: lr:hq
minimap_pb: map-hifi
minimap_il: sr
minimap_ram: 50
minimap_ref: 10
minimap_ratio: 0.8
mapping_usage: 20
min_contig_len: 3000
min_contig_cov: 0
min_mag_len: 250000
min_smag_len: 1000000
semibin_mod: global
semibin_prot: prodigal
np_map_ident: 95
pb_map_ident: 97
il_map_ident: 97
min_compl_circ: 80
min_compl_lin: 90
min_compl_checkm1: 50
min_compl_1: 90
min_compl_2: 50
min_cont_singl: 10
min_cont_checkm1: 10
min_cont_1: 5
min_cont_2: 10
binette_weight: 5
min_score_checkm1: 30
cov_method: mean
cleanup_status: TRUE
apptainer_status: TRUE
env_1: env_1
env_2: env_2
env_3: env_3
env_4: env_4
env_5: env_5
env_6: env_6
env_7: env_7
env_8: env_8
env_9: env_9
