version: 1.1.0
zenodo_id: 11499494
sample: mmlong2
loc: none
sing: none
fastq: none
reads_diffcov: none
mode: Nanopore-simplex
seed: 15690701
proc: 3
proc_sub: 5
flye_cov: 3
flye_ovlp: 0
mdbg_status: FALSE
minimap_np: map-ont
minimap_pb: map-hifi
minimap_il: sr
minimap_ram: 50
minimap_ref: 10
mapping_usage: 20
min_contig_len: 3000
max_contig_con: 20
inc_contig_len: 50000
min_mag_len: 250000
min_smag_len: 1000000
medaka_status: TRUE
medaka_split: 30
medaka_usage: 10
medak_mod_pol: r1041_e82_400bps_sup_v5.0.0
vamb_status: FALSE
semibin_mod: global
semibin_prot: prodigal
np_map_ident: 90
pb_map_ident: 97
il_map_ident: 97
min_compl_circ: 80
min_compl_lin: 90
min_compl_checkm1: 50
min_compl_1: 90
min_compl_2: 50
min_compl_3: 50
min_compl_4: 50
min_cont_singl: 10
min_cont_checkm1: 10
min_cont_1: 5
min_cont_2: 10
min_cont_3: 10
min_cont_4: 10
min_score_checkm1: 30
das_tool_score_1: 0.5
das_tool_score_2: 0.5
das_tool_score_3: 0
cov_method: mean
apptainer_status: TRUE
env_1: env_1
env_2: env_2
env_3: env_3
env_4: env_4
env_5: env_5
env_6: env_6
env_7: env_7
env_8: env_8
