version: 1.2.1
zenodo_id: 17256971
sample: mmlong2
loc: none
fastq: none
sing: sing
proc: 3
proc_sub: 5
split_max: 30
mode: Nanopore-simplex
db_gtdb: /path/to/gtdb/database_dir
db_bakta: /path/to/bakta/database_dir
db_rrna: /path/to/rrna/database_file.udb
db_metabuli: /path/to/metabuli/database_dir
db_gunc: /path/to/gunc/database_file.dmnd
db_barrnap: arc
db_trnascan: A
dl_bakta: https://zenodo.org/records/14916843/files/db.tar.xz
dl_gtdb: https://data.ace.uq.edu.au/public/gtdb/data/releases/release226/226.0/auxillary_files/gtdbtk_package/full_package/gtdbtk_r226_data.tar.gz
dl_rrna: https://zenodo.org/records/17174373/files/greengenes2_2024.09.udb.gz
dl_metabuli: https://hulk.mmseqs.com/jaebeom/gtdb226db/
dl_gunc: https://swifter.embl.de/~fullam/gunc/gunc_db_progenomes2.1.dmnd.gz
link_metabuli: https://dev.mmseqs.com/metabuli/metabuli-linux-avx2.tar.gz
min_len_ssu: 500
min_id_ssu: 0.75
ssu: 16S
bakta_extra: FALSE
bakta_usage: 5
trnascan_usage: 2
longshot_usage: 10
min_cov: 6
min_mapq: 18
min_frac: 0.1
min_count: 3
cleanup_status: TRUE
apptainer_status: TRUE
env_10: env_10
env_11: env_11
env_12: env_12
env_13: env_13
env_14: env_14
