version: 1.0.2
sample: mmlong2
sing: none
fastq: none
reads_diffcov: none
mode: Nanopore-simplex
proc: 3
flye_cov: 3
flye_ovlp: 0
minimap_ram: 50
minimap_ref: 10
min_contig_len: 3000
max_contig_con: 18
inc_contig_len: 120000
min_mag_len: 250000
medaka_split: 20
medak_mod_pol: r1041_e82_400bps_sup_v4.2.0
semibin_mod: global
semibin_prot: prodigal
np_map_ident: 90
pb_map_ident: 97
il_map_ident: 97
min_compl_1: 90
min_compl_2: 50
min_compl_3: 50
min_compl_4: 50
min_cont_1: 5
min_cont_2: 10
min_cont_3: 10
min_cont_4: 10
das_tool_score_1: 0.5
das_tool_score_2: 0.5
das_tool_score_3: 0
