version: 1.1.0
zenodo_id: 11563692
sample: mmlong2
loc: none
fastq: none
sing: sing
proc: 3
proc_sub: 5
split_max: 30
mode: Nanopore-simplex
db_gtdb: /databases/gtdb-tk/release220/gtdb-tk
db_bakta: /projects/microflora_danica/mmlong2/db/bakta_v5.1
db_rrna: /projects/microflora_danica/mmlong2/db/MiDAS_v5.3.0_sintax.fasta
db_kaiju: /projects/microflora_danica/mmlong2/db/kaiju_db_nr_2023-05-10
db_gunc: /projects/microflora_danica/mmlong2/db/gunc_db_progenomes2.1.dmnd
db_barrnap: arc
db_trnascan: A
dl_bakta: https://zenodo.org/records/10522951/files/db.tar.gz
dl_gtdb: https://data.ace.uq.edu.au/public/gtdb/data/releases/release220/220.0/auxillary_files/gtdbtk_package/full_package/gtdbtk_r220_data.tar.gz
dl_rrna: https://www.midasfieldguide.org/files/downloads/taxonomies/SINTAX.fa%20MiDAS%205.3.fa
dl_kaiju: https://kaiju-idx.s3.eu-central-1.amazonaws.com/2023/kaiju_db_nr_2023-05-10.tgz
dl_gunc: https://swifter.embl.de/~fullam/gunc/gunc_db_progenomes2.1.dmnd.gz
min_len_ssu: 1000
min_id_ssu: 0.7
ssu: 16S
bakta_extra: FALSE
bakta_usage: 5
trnascan_usage: 2
longshot_usage: 10
min_cov: 6
min_mapq: 18
min_frac: 0.1
min_count: 3
apptainer_status: TRUE
env_9: env_9
env_10: env_10
env_11: env_11
env_12: env_12
env_13: env_13
